services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Ajuste la mémoire selon les besoins
      - xpack.security.enabled=false    # Désactive la sécurité pour un usage local
    ports:
      - "9200:9200"  # Port d'accès à Elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data  # Persistance des données

volumes:
  es_data:
    driver: local